### ISSUE TITLE
[Feature request] Use Clap: Command Line Argument Parser for Rust 

### ISSUE THREAD

**Issue by costincaraivan** [danielthegray/vaultfile#1]
It might be interesting to use clap for the CLI: https://github.com/clap-rs/clap

Among the very nice features:
> Auto-generated completion scripts (Bash, Zsh, Fish, Elvish and PowerShell)

**Comment by danielthegray** [comment]
I have integrated clap as a dependency and implemented the first subcommand with it. All other elements will be implemented with clap, so I will close the issue. Thanks for the input! It was definitely a good idea.
