### ISSUE TITLE
[Feature request] Sub-command CLI style

### ISSUE THREAD

**Issue by costincaraivan** [danielthegray/vaultfile#2]
Most tools become more complex over time. It might be useful to start directly with subcommands, à la awscli, git, etc. What I mean:

> vaultfile --new-key[=new_key_name]
would become:
> vaultfile new-key [new_key_name]

This will make things easier to manage and less confusing as more commands are added, parameters, flags, etc.

**Comment by danielthegray** [comment]
I have added `generate-key` as the first subcommand, and all future elements will also be implemented as subcommands (and the relevant help sections will also be corrected). Therefore, I will also close this issue. Thanks for this great suggestion!
